# Step 1: Use an official PHP image with FPM and necessary extensions
FROM php:8.2-fpm

# Step 2: Install system dependencies (e.g., for handling images, cache, and DB connection)
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    git \
    unzip \
    curl \
    libicu-dev \
    cron \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip intl

# Step 3: Set the working directory for the application
WORKDIR /var/www

# Step 4: Copy application code into the container
COPY . .

# Step 5: Install Composer (PHP package manager) globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Step 6: Install PHP dependencies with Composer (Laravel's dependencies)
RUN composer install --no-interaction --optimize-autoloader --prefer-dist

# Step 7: Set appropriate file permissions for Laravel
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Step 8: Expose port 9000 (default PHP-FPM port)
EXPOSE 9000

# Step 9: Start PHP-FPM (the default entrypoint for this image)
CMD ["php-fpm"]
