# nixpacks.toml

[build]
builder = "nixpacks"

[env]
# Environment variables that you may need for your Laravel app

DB_CONNECTION = "mysql"
DB_HOST = "i8s0kkc404ccw0kcwo8w48sw"
DB_PORT = "3306"
DB_DATABASE = "laravel_coolify"
DB_USERNAME = "mysql"
DB_PASSWORD = "n94m0JQVFx6X4X0kJEKDbCZyf7yBmb1v40vlNBwfYJJZpJmb0adcRLtKr8BBQXJb"



APP_KEY = "base64:U7cZtf96pnPY1KyxqEDx5wzebI1QLx4RdbqV8RhkBOU="

[services]
# Expose the HTTP port where Laravel will run (default is 80)
http = { port = 80 }
